# Welcome to Jekyll!

########### Global Variables ###########
title: 'Tapsell: Smart ad network agency'
email: technical.tapsell@gmail.com
description: >-
  Tapsell, by dominating a great extent of digital media network and giving various advertising campaigns, is capable of meeting the expectation of the most valuable brands. Additionally, by showing the advertisements to the subscribers in a smart way, we bring a long- lasting and remarkable revenue without any damage to media owners’ practical experience.
baseurl: '' # the subpath of your site, e.g. /docs
url: 'https://tapsell.ir'
twitter_username: 
github_username: tapsellorg
site_name: Tapsell
global_vars:
  landing_url: https://tapsell.ir
  dashboard_url: https://dashboard.tapsell.ir/
  blog_url: https://college.tapsell.ir/
  docs_url: https://docs.tapsell.ir/
  site_name: Tapsell
  get_demo_url: https://dashboard.tapsell.ir/
  terms_url: https://tapsell.ir/
  header_logo_alt: Tapsell Docs
  contact_email: info@tapsell.ir
  footer_logo_alt: Tapsell

########### Condfigurations ###########

# Jekyll Configurations: https://jekyllrb.com/docs/configuration/options/
source: src/jekyll

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-toc
  - jekyll-minifier

# jekyll-polyglot settings
languages: ['en', 'fa']
default_lang: 'fa'
exclude_from_localizations: ['javascript', 'images', 'css']
parallel_localization: true

# jekyll-minifier settings
jekyll-minifier:
  exclude: 'feed.xml'
  uglifier_args:
    harmony: true

########### Translations ###########
t:
  en:
    nav:
      home: Home
      dashboard: Dashboard
      get_demo: Get a Demo
      blog: Blog
    footer:
      terms: Terms of Service
      contact: Contact Us
      copyright: Designed and Developed by Tapsell - Iran
  fa:
    nav:
      home: خانه
      dashboard: داشبورد
      get_demo: دریافت دمو
      blog: وبلاگ
    footer:
      terms: قوانین
      contact: تماس با ما
      copyright: طراحی و توسعه توسط تپسل - ایران
