# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 'Frasco: Jekyll Starter Project'
email: your-email@domain.com
description: >-
  Metrix is a mobile marketing measurement platform that unifies mobile attribution and analytics into one powerful platform.
baseurl: '' # the subpath of your site, e.g. /docs
url: 'https://metrix.ir' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Metrix_ir
github_username: metrixorg
site_name: Metrix

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-toc
  - jekyll-minifier

# jekyll-polyglot settings
languages: ['en', 'fa']
default_lang: 'fa'
exclude_from_localizations: ['javascript', 'images', 'css']
parallel_localization: true

# jekyll-minifier settings
jekyll-minifier:
  exclude: 'feed.xml'
  uglifier_args:
    harmony: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - frasco.config.js
  - webpack.config.js
  - Gemfile
  - Gemfile.lock
  - gulp_tasks
  - gulpfile.js
  - LICENSE
  - node_modules
  - npm-debug.log
  - package.json
  - package-lock.json
  - README.md
  - vendor
  - yarn.lock
  - .jekyll-cache
  - src/sass
  - src/js
  - src/assets

# keep_files:
#   - assets

# Global Variables
global_vars:
  landing_url: https://metrix.ir
  dashboard_url: https://dashboard.metrix.ir
  blog_url: https://blog.metrix.ir
  docs_url: https://metrix.ir/docs
  site_name: Metrix
  get_demo_url: https://dashboard.metrix.ir/login/demo
  terms_url: https://metrix.ir/terms
  header_logo_alt: Metrix Docs
  contact_email: info@metrix.ir
  footer_logo_alt: Metrix

# Translations
t:
  en:
    nav:
      home: Home
      dashboard: Dashboard
      get_demo: Get a Demo
      blog: Blog
    footer:
      terms: Terms of Service
      contact: Contact Us
      copyright: Designed and Developed by Metrix - Iran
  fa:
    nav:
      home: خانه
      dashboard: داشبورد
      get_demo: دریافت دمو
      blog: وبلاگ
    footer:
      terms: قوانین
      contact: تماس با ما
      copyright: طراحی و توسعه توسط متریکس - ایران
