# Site settings
title: "CircleCI Documentation"
email: docs@cirleci.com
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for CircleCI, the fastest testing platform on the
  Internet.

baseurl: "" # the subpath of your site, e.g. /blog
gh_url: "https://github.com/circleci/circleci-docs"

plugins:
  - jekyll-assets
  - jekyll-polyglot
  # - jekyll-multiple-languages-plugin

languages: ["en", "fa"]
default_lang: "fa"
exclude_from_localizations: ["javascript", "images", "css"]
parallel_localization: true

algolia:
  application_id: U0RXNGRK45
  index_name: documentation
  settings:
    highlightPreTag: '<strong>'
    highlightPostTag: '</strong>'
    attributesToSnippet: [
      'content:80',
      'headings',
      'title'
    ]
    attributesToHighlight: [
      'content:80',
      'headings',
      'title'
    ]

sass:
  sass_dir: _sass

markdown: kramdown
kramdown:
  input: GFM

liquid:
  error_mode: strict

collections:
  # jekyll processes in alpha order...
  docs:
    permalink: "/:collection/:path/"
    output: true

twitter_username: circleci
github_username: circleci

# defaults:
#   -
#     scope:
#       path: ""
#       type: "cci2"
#     values:
#       lang: "en"

#   -
#     scope:
#       path: ""
#       type: "cci2_ja"
#     values:
#       lang: "ja"

#   -
#     scope:
#       path: ""
#     values:
#       hide: false
#       search: true

# segment: 'mAJ9W2SwLHgmJtFkpaXWCbwEeNk9D8CZ'

# analytics:
#   events:
#     go_button_clicked: go-button-clicked
# rollbar_env: development

global_vars:
  landing_url: https://metrix.ir
  dashboard_url: https://dashboard.metrix.ir
  blog_url: https://blog.metrix.ir
  docs_url: https://docs.metrix.ir
  site_name: Metrix
  get_demo_url: https://dashboard.metrix.ir/login/demo