version: 2

jobs:
  deploy-website:        
    docker:
      # specify the version you desire here
      - image: circleci/node:12.14.1

    steps:
      - checkout
      - run:
          name: Install Ruby
          command: |
            sudo apt-get install ruby-full
            sudo gem install bundler
            ruby -v
            bundle install

      - run: npm install

      - run:
          name: Build
          command: |
            npm run build

      - run:
          name: CNAME config
          command: |
            echo "docs.tapsell.ir" > _site/CNAME

      - run:
          name: git configure
          command: |
            git config --global user.email "technical.tapsell@gmail.com"
            git config --global user.name "tapsellCI"

      - run:
          name: Deploying to GitHub Pages
          command: |
            git clone git@github.com:tapsellorg/TapsellDocument.git

            cd TapsellDocument
            git checkout gh-pages

            rm -rf *
            mv ../_site/* .

            git add -A
            git commit -am "update gh pages"
            git push

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              only: master

