backend:
  name: gitlab
  repo: my-personal-work-life/tapsell-doc-temporary # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: 7e9b2cbccdf26d85c7bad0c1cd9ff423f641e7b026e16be56c65ae65e91dbb23 # Application ID from your GitLab settings
media_folder: 'src/jekyll/images'
collections:
  - name: 'data'
    label: 'Data'
    delete: false
    files:
      - label: 'Sidebar'
        delete: false
        name: 'sidebar'
        file: 'src/jekyll/_data/sidebar.yml'
        extension: yml
        fields:
          - label: English
            name: en
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Children
                name: children
                widget: list
                allow_add: true
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Children
                    name: children
                    widget: list
                    allow_add: true
                    fields:
                      - label: Name
                        name: name
                        widget: string
          - label: Persian
            name: fa
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string
              - label: Icon
                name: icon
                widget: string
              - label: Children
                name: children
                widget: list
                allow_add: true
                fields:
                  - label: Name
                    name: name
                    widget: string
                  - label: Children
                    name: children
                    widget: list
                    allow_add: true
                    fields:
                      - label: Name
                        name: name
                        widget: string
